# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/upgraded-octo-adventure',
                'doc_host': 'https://JoyChristine.github.io',
                'git_url': 'https://github.com/JoyChristine/upgraded-octo-adventure',
                'lib_path': 'upgraded_octo_adventure'},
  'syms': {'upgraded_octo_adventure.core': {'upgraded_octo_adventure.core.foo': ('core.html#foo', 'upgraded_octo_adventure/core.py')}}}
